### PR TITLE
Performance tweaks, fix incorrect `runningTests`, include snapshot of save-cli

### LINKED ISSUE #489: Orchestrator: Add back setting `--include-suite` flag in standard mode
After https://github.com/diktat-static-analysis/save/pull/340 it will improve performance

### LINKED ISSUE #491: Incorrect concurrent setting of `runningTetss` counter
```
  |   | 2021-12-15 19:08:06 | save_backend.1.rgnld36uwor22bij8a2711qdy | 16:08:06.131 [parallel-1] DEBUG o.c.save.backend.service.TestService - Updating counter for running tests: 50 -> 100
  |   | 2021-12-15 19:08:05 | save_backend.1.rgnld36uwor22bij8a2711qdy | 16:08:05.985 [parallel-2] DEBUG o.c.save.backend.service.TestService - Updating counter for running tests: 0 -> 50
  |   | 2021-12-15 19:08:05 | save_backend.1.rgnld36uwor22bij8a2711qdy | 16:08:05.912 [parallel-1] DEBUG o.c.save.backend.service.TestService - Updating counter for running tests: 0 -> 50
```

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* To properly integrate https://github.com/diktat-static-analysis/save/pull/340, closes #489.
* Closes #491
* Added configuration to include snapshot of save-cli into docker images (always builds save-cli in the same workflow, needs to be fixed, once we are back to using release versions)
* Enable batch operations in Hibernate
* Measure time spent in `saveTests` and `saveTestExecution`
* Disable default debug logging
* Externalize configuration for quartz schedule
* `TestService`: don't query joined entity to access `testSuiteId`

### CODE REVIEW

File: save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt [hunk 1]
```diff
@@ -75,7 +75,9 @@ class SaveAgent(internal val config: AgentConfiguration,
      */
     suspend fun start() = coroutineScope {
         logInfoCustom("Starting agent")
-        val heartbeatsJob = launch { startHeartbeats() }
+        val heartbeatsJob = launch(newSingleThreadContext("heartbeats")) {
```
Comment (petertrr) [inline save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt:78]: This still doesn't help with heartbeats during process execution

File: save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt [hunk 2]
```diff
@@ -74,16 +74,22 @@ class TestService(
...
         val agent = agentRepository.findByContainerId(agentId) ?: error("The specified agent does not exist")
         log.debug("Agent found, id=${agent.id}")
-        val execution = agent.execution
-        val lock = locks.computeIfAbsent(execution.id!!) { Any() }
+        val executionId = agent.execution.id!!
+        val lock = locks.computeIfAbsent(executionId) { Any() }
         return synchronized(lock) {
+            log.debug("Acquired lock for executionId=$executionId")
             val testExecutions = transactionTemplate.execute {
+                val execution = executionRepository.getById(executionId)
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt:82]: Turns out, execution must be read inside the same transaction, where it will be modified.

File: save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt [hunk 3]
```diff
@@ -91,7 +91,7 @@ class SaveAgent(internal val config: AgentConfiguration,
                 sendHeartbeat(ExecutionProgress(0))
             }
             if (response.isSuccess) {
-                when (val heartbeatResponse = response.getOrNull().also {
+                when (val heartbeatResponse = response.getOrThrow().also {
```
Comment (petertrr) [inline save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt:94]: This fixes compiler warning about non-exhaustive `when`, because there should be a separate branch for `null`. However, we check `response.isSuccess`, so `null` will never be returned.

File: save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt (hunk 2 above)
Comment (akuleshov7) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestService.kt:82]: extremely strange. 70% sure that is not the reason

**Review by akuleshov7 — APPROVED** [review]
